version: '2.1'

services:
  db:
    image: "postgres"
    container_name: "pgdb"
    environment:
      - POSTGRES_USER=raicerk
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
  mentores-ti-api:
    image: mentores-ti-api
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000